# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/build/ss
  - cd ~/build/ss

script:
  - vendor/bin/phpunit checkio-integration/tests
