# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.2

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/build/ss
  - cd ~/build/ss
  - composer install

script:
  - vendor/bin/phpunit checio-integration/tests/
